<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Yamazaki</title>
    <link rel="stylesheet" href="template/master.css">
    <link rel="stylesheet" href="template/menu.css">
  </head>
  <body>
    <div class="HeadNav">
      <header>
        <h1>
          Yamazaki
        </h1>
        <h2>
          Sushi & Hibachi
        </h2>
      </header>
<!--      <nav>
        <ul>
          <li><a href="Home.html">Home</a></li>
          <li><a href="Menu.html">Menu</a></li>
          <li><a href="Catering.html">Catering</a></li>
          <li><a href="Specials.html">Specials</a></li>
          <li><a href="Feedback.html">Feedback</a></li>
        </ul>
      </nav>-->
        <h1 class="foodMenu">~Menu~</h1>
        <nav id=NavMenu>
          <ul>
            <button onclick="activateMenu('Appetizer')">Appetizer</button>
            <button onclick="activateMenu('Entree')">Entr&eacutee</button>
            <button onclick="activateMenu('Sushi')">Sushi</button>
            <button onclick="activateMenu('Lunch')">Lunch</button>
            <button onclick="activateMenu('Kids')">Kids</button>
            <button onclick="activateMenu('Desserts')">Desserts</button>
            <button onclick="activateMenu('Drinks')">Drinks</button>
          </ul>
        </nav>
      </div>
      <div class="bodyContent">
      <table id="Appetizer">
        <caption>Appetizers</caption>
        <tr>
          <th colspan="12" class="Subsection"></th>
        </tr><tr>
          <td>Vegetable Spring Roll(2)</td><td> 2.99</td><td></td>
          <td>Edame</td><td>&nbsp; 4.50</td><td></td>
          <td>Goryza(6)</td><td> 4.50</td>
        </tr><tr>
          <td>Shumai(6)</td><td> 4.95</td><td></td>
          <td>Crab Rangoon(6)</td><td>&nbsp; 5.25</td><td></td>
          <td>Fried Green Bean</td><td> 6.50</td>
        </tr><tr>
          <td>Avocado Tempura(6)</td><td> 4.95</td><td></td>
          <td>Fried Soft Shell Crab</td><td>&nbsp; 6.95</td><td></td>
          <td>Tempura Appetizer Vegetable(10)</td><td> 4.25</td><td></td>
        </tr><tr>
          <td>Tempura Appetizer Shrimp(3)</td><td> 5.95</td><td></td>
          <td>Tempura Appetizer Chicken(3)</td>   <td colspan="2" >&nbsp; 5.75</td>
          <td>Chicken Katsu</td>                  <td colspan="2"> 5.25</td>
        </tr><tr>
          <td>Salt&Pepper Calamari</td><td> 8.95</td><td></td>
          <td> Yamazaki Sampler</td>              <td colspan="2"> 12.95</td>
          <td>Coconut Shrimp(6)</td>              <td colspan="2"> 7.95</td>
        </tr><tr>
          <td>Yaki Ebi(2)</td>                    <td colspan="2">7.95 </td>
          <td>Hot wings(6)</td>                   <td colspan="2">&nbsp; 7.95</td>
        </tr><tr>
          <th colspan="9" class="Subsection">Sushi Bar Appetizers</th>
        </tr><tr>
          <td>Sushi(5)</td><td> 7.95</td><td></td>
          <td>Sashimi(8)</td><td>&nbsp; 8.95</td><td></td>
          <td>Yellowtail Jalapeno(6)</td><td> 8.95</td>
        </tr><tr>
          <td>Tuna Tataki(8)</td><td> 8.95</td><td></td>
          <td>Pepper Tuna(8)</td><td>&nbsp; 8.50</td><td></td>
          <td>Sesame Tuna(8)</td><td> 8.95</td>
        </tr><tr>
          <td colspan="3"></td>
          <td>Tako Su(6)</td>                     <td colspan="2"> 6.95</td>
        </tr><tr>
          <th colspan="9" class="Subsection">Soup & Salads</th>
        </tr><tr>
          <td>Onion Soup</td><td> 1.99</td><td></td>
          <td>Miso Soup</td><td> &nbsp; 1.99</td><td></td>
          <td>House Salad</td><td> 1.99</td>
        </tr><tr>
          <td>Cucumber Salad</td><td> 4.50</td><td></td>
          <td>Avocado Salad</td><td>&nbsp; 5.25</td><td></td>
          <td>Seaweed Salad</td><td> 4.95</td>
        </tr><tr>
          <td>Squid Salad</td><td> 5.50</td><td></td>
          <td>Crab Stick Salad</td><td>&nbsp; 4.95</td><td></td>
          <td>Spicy Tuna Avocado Salad</td><td>7.95</td>
        </tr><tr>
          <td>Egg Drop Soup</td>                  <td colspan="2">2.75</td>
          <td>Sashimi Avocado Salad</td><td>10.95</td><td></td>
          <td>Hot Sour Soup</td>                  <td colspan="2">3.75</td>
        </tr><tr>
          <th colspan="9" class="Subsection">Side Orders</th>
        </tr><tr>
          <td>Steamed Rice</td><td> 1.99</td><td></td>
          <td>Fried Rice</td><td>&nbsp; 2.55</td><td></td>
          <td>Sushi Rice</td><td>2.55</td>
        </tr><tr>
          <td>Vegetables</td><td> 3.25</td><td></td>
          <td>Chicken</td><td>&nbsp; 4.55</td><td></td>
          <td>Shrimp</td><td>5.95</td>
        </tr><tr>
          <td>Scallop</td><td> 5.95</td><td></td>
          <td>Salmon</td><td>&nbsp; 5.95</td><td></td>
          <td>Steak*</td><td>7.95</td>
        </tr><tr>
          <td></td><td></td><td></td>
          <td>Lobster</td><td>&nbsp; 6.95</td><td></td>
          <td></td><td></td>
        </tr>
      </table>
      <table id="Entree">
        <caption>Entr&eacutee</caption>
        <!--<caption class="subCap">Rice&Noodle</caption>-->
        <tr>
          <th colspan="12" class="Subsection">Rice&Noodle</th>
        </tr><tr>
          <th colspan="12" class="SubSect2"> Served with Soup or Salad</th>
        </tr><tr>
          <th colspan="3" class="SubSect2"> Fried rice</th>
          <th colspan="3" class="SubSect2"> Lo Mein</th>
          <th colspan="3" class="SubSect2"> Soba</th>
          <th colspan="3" class="SubSect2"> Udon(Stir Fri or Soup)</th>
        </tr><tr><!--Vegetable-->
          <td>Vegetable Fried Rice</td><td>&nbsp; 8.95</td><td></td>
          <td>Vegetable Lo Mein</td><td>&nbsp; 8.95</td><td></td>
          <td>Vegetable Soba</td><td>&nbsp; 8.95</td><td></td>
          <td>Vegetable Udon</td><td>&nbsp; 8.95</td><td></td>
        </tr><tr><!--Chicken-->
          <td>Chicken Fried Rice</td><td>&nbsp; 9.95</td><td></td>
          <td>Chicken Lo Mein</td><td>&nbsp; 9.95</td><td></td>
          <td>Chicken Soba</td><td>&nbsp; 9.95</td><td></td>
          <td>Chicken Udon</td><td>&nbsp; 9.95</td><td></td>
        </tr><tr><!--Shrimp-->
          <td>Shrimp Fried Rice</td><td> 11.95</td><td></td>
          <td>Shrimp Lo Mein</td><td> 11.95</td><td></td>
          <td>Shrimp Soba</td><td> 11.95</td><td></td>
          <td>Shrimp Udon </td><td> 11.95</td><td></td>
        </tr><tr><!--Stake-->
          <td>Steak* Fried Rice</td><td> 12.95</td><td></td>
          <td>Steak* Lo Mein</td><td> 12.95</td><td></td>
          <td>Steak* Soba</td><td> 12.95</td><td></td>
          <td>Steak* Udon </td><td> 12.95</td><td></td>
        </tr><tr><!--Combo-->
          <td>Combo Fried Rice</td><td> 15.50</td><td></td>
          <td>Combo Lo Mein</td><td> 15.50</td><td></td>
          <td>Combo Soba</td><td> 15.50</td><td></td>
          <td>Combo Udon </td><td> 15.50</td><td></td>
        </tr><tr>
          <td colspan="9"></td>
          <td> Shrimp Tampura Udon(6)</td><td colspan="2">12.95</td>
        </tr><tr>
          <th colspan="12" class="Subsection"> Tempura </th>
        </tr><tr>
          <th colspan="12" class="SubSect2"> Served with Soup, Salad, and rice (Steamed or Fried)</th>
        </tr><tr>
          <td>Vegetable Tempura</td><td>10.95</td><td></td>
          <td>Chicken Tempura</td><td>11.95</td><td></td>
          <td>Shrimp Tempura</td><td>13.95</td><td></td>
          <td>Chicken Katsu</td><td>12.95</td><td></td>
        </tr><tr><!--
          <th colspan="12" class="Subsection"> Teriyaki </th>
        </tr><tr>
          <th colspan="12" class="SubSect2"> Served with Soup, Salad, and rice (Steamed or Fried)</th>
        </tr><tr>
          <td>Tofu </td><td> &nbsp; 9.95</td><td></td>
          <td>Chicken</td><td>11.95</td><td></td>
          <td>Shrimp</td><td>12.95</td><td></td>
          <td>Salmon</td><td>13.95</td><td></td>
        </tr><tr>
          <td>Scallop</td><td>14.95</td><td></td>
          <td>Steak</td><td>14.95</td><td></td>
          <td>Lobster</td><td>16.95</td><td></td>
          <td>Chicken & Shrimp</td><td>16.95</td><td></td>
        </tr><tr>
          <td>Chicken & Salmon </td><td>17.95</td><td></td>
          <td>Chicken & Scallop</td><td>18.95</td><td></td>
          <td>Shrimp & Scallop</td><td>20.95</td><td></td>
          <td>Lobster & Shrimp</td><td>22.95</td><td></td>
        </tr><tr>-->
          <th colspan="12" class="Subsection">Hibachi</th>
        </tr><tr>
          <th colspan="12" class="SubSect2"> Served with Soup, Salad, and rice (Steamed or Fried)</th>
        </tr><tr>
          <td>Vegetable</td><td>&nbsp;9.95</td><td></td>
          <td>Tofu</td><td>10.95</td><td></td>
          <td>Chicken</td><td>12.95</td><td></td>
          <td>Shrimp(10)</td><td>13.95</td><td></td>
        </tr><tr>
          <td>Salmon</td><td>13.95</td><td></td>
          <td>Scallop(6)</td><td>13.95</td><td></td>
          <td>Steak*</td><td>15.95</td><td></td>
          <td>Lobster(2)</td><td>15.95</td><td></td>
        </tr><tr>
          <td>Chicken & Shrimp </td><td>17.95</td><td></td>
          <td>Chicken & Salmon </td><td>17.95</td><td></td>
          <td>Chicken & Scallop </td><td>17.95</td><td></td>
          <td>Chicken & Steak* </td><td>18.95</td><td></td>
        </tr><tr>
          <td>Chicken & Lobster </td><td>19.95</td><td></td>
          <td>Shrimp & Salmon </td><td>20.95</td><td></td>
          <td>Shrimp & Scallop</td><td>20.95</td><td></td>
          <td>Shrimp & Steak*</td><td>21.95</td><td></td>
        </tr><tr>
          <td>Shrimp & Lobster </td><td>21.95</td><td></td>
          <td>Salmon & Scallop </td><td>20.95</td><td></td>
          <td>Salmon & Steak*</td><td>21.95</td><td></td>
          <td>Salmon & Lobster</td><td>21.95</td><td></td>
        </tr><tr>
          <td>Scallop & Steak* </td><td>21.95</td><td></td>
          <td>Scallop & Lobster </td><td>21.95</td><td></td>
          <td>Sea Sea Sea <span>(Shrimp,Salmon,Scallop)</span> </td><td>27.95</td><td></td>
          <td>Imperial Fest <span>(Shrimp,Salmon,Scallop,Lobster)</span> </td><td>34.95</td><td></td>
        </tr><tr>
          <th colspan="12" class="Subsection">Bento Box</th>
        </tr><tr>
          <th colspan="12" class="SubSect2"> Served with Soup, Salad, and rice (Steamed or Fried)</th>
        </tr><tr>
          <th colspan="12" class="SubSect2"> 2pc of Gyoza, 2pc Spring Roll, 8pc California Roll</th>
        </tr><tr>
          <td>Teriyaki Chicken & Shrimp </td><td>18.95</td><td></td>
          <td>Teriyaki Chicken & Salmon </td><td>18.95</td><td></td>
          <td>Teriyaki Chicken & Steak*</td><td>20.25</td><td></td>
          <td>Teriyaki Steak* & Shrimp</td><td>21.25</td><td></td>
        </tr><tr>
          <td>Teriyaki Salmon & Steak* </td><td>21.25</td><td></td>
          <td>Teriyaki Scallop & Shrimp </td><td>20.95</td><td></td>
          <td>Teriyaki Shrimp & Salmon</td><td>20.95</td><td></td>
          <td>Shrimp & Chicken Tempura</td><td>19.95</td><td></td>
        </tr><tr>
          <td></td><td></td><td></td>
          <td>Sashimi Bento* (12) </td><td>17.95</td><td></td>
          <td>Sushi Bento* (8)</td><td>16.95</td><td></td>
          <td></td><td></td><td></td>
        </tr>
      </table>
      <table id="Sushi">
        <caption>Sushi</caption>
        <tr>
          <th colspan="12" class="Subsection">Sushi Bar Entr&eacutee</th>
        </tr><tr>
          <th colspan="12" class="SubSect2"> Served with Soup or Salad</th>
        </tr><tr>
          <td>Maki Combo*</td>                    <td>13.95</td><td></td>
          <td>Spicy Maki Combo*</td>              <td>13.95</td><td></td>
          <td>Sushi Regular*</td>                 <td>15.95</td><td></td>
          <td>Sushi Deluxe*</td>                  <td>17.95</td><td></td>
        </tr><tr>
          <td>Sashimi Regular*</td>               <td>18.95</td><td></td>
          <td>Sashimi Deluxe*</td>                <td>21.95</td><td></td>
          <td>Sushi Sashimi Combo*</td>           <td>24.95</td><td></td>
          <td>Tekka Don*</td>                     <td>19.95</td><td></td>
        </tr><tr>
          <td>Sake Don*</td>                      <td>19.95</td><td></td>
          <td>Unagi Don*</td>                     <td>15.95</td><td></td>
          <td>Sushi For Two*</td>                 <td>33.95</td><td></td>
          <td>Love Boat for two*</td>             <td>44.95</td><td></td>
        </tr><tr>
          <th colspan="12" class="Subsection">Clasic Rolls</th>
        </tr><tr>
          <th colspan="12" class="SubSect2">Substitute: Brown Rice 0.5 Extra, Soybeen Wrap 1.00 Extra </th>
        </tr><tr>
          <td> Alaska Roll*</td>                  <td> 7.50</td><td></td>
          <td> California Roll </td>              <td> 4.75 </td><td></td>
          <td> Eel Avocado Roll </td>             <td> 5.50 </td><td></td>
          <td> Tuna Roll*</td>                    <td> 5.50 </td><td></td>
        </tr><tr>
          <td> Salmon Roll*</td>                  <td> 5.50</td><td></td>
          <td> Philly Roll*</td>                  <td> 5.50</td><td></td>
          <td> Shrimp Roll </td>                  <td> 4.75 </td><td></td>
          <td> Snow Crab Roll </td>               <td> 5.25 </td><td></td>
        </tr><tr>
          <td> Shrimp Tempura Roll </td>          <td> 6.50 </td><td></td>
          <td> Sweet Potato Roll </td>            <td> 4.95 </td><td></td>
          <td> Crab Tempura Roll </td>            <td> 4.50 </td><td></td>
          <td> Chicken Tempura Roll </td>         <td> 6.25</td><td></td>
        </tr><tr>
          <td> Salmon Tempura Roll </td>          <td> 6.50</td><td></td>
          <td> Vegetable Tempura Roll </td>       <td>5.50 </td><td></td>
          <td> Spider Roll Tempura </td>          <td> 6.95</td><td></td>
          <td> Easter Roll </td>                  <td>5.25 </td><td></td>
        </tr><tr>
          <td> Boston Roll </td>                  <td> 5.25 </td><td></td>
          <td> Salmon Skin Roll </td>             <td> 4.95 </td><td></td>
          <td> Mixed Vegetable Roll </td>         <td> 4.95 </td><td></td>
          <td> A.A.C Roll </td>                   <td>4.95 </td><td></td>
        </tr><tr>
          <td> Rainbow Roll*</td>                 <td> 9.50 </td><td></td>
          <td> Dragon Roll </td>                  <td> 9.75 </td><td></td>
          <td> Tokyo Roll </td>                   <td> 7.95 </td><td></td>
          <td> Crispy Salmon Roll* </td>          <td>7.95 </td><td></td>
        </tr><tr>
          <td> Fantastic Roll </td>               <td> 8.75 </td><td></td>
          <td> Crunch Roll </td>                  <td> 7.25 </td><td></td>
          <td> Salmon Lover Roll*</td>            <td> 9.50</td><td></td>
          <td> Naruto Roll </td>                  <td> 8.25</td><td></td>
        </tr><tr>
          <td> Ocean Roll*</td>                   <td> 9.95 </td><td></td>
          <td> Spicy Tuna Roll*</td>              <td> 5.50 </td><td></td>
          <td> Spicy Salmon Roll* </td>           <td> 5.50 </td><td></td>
          <td> Spicy Yellowtail Roll* </td>       <td> 4.95</td><td></td>
        </tr><tr>
          <td> Spicy Shrimp Roll </td>            <td> 4.95 </td><td></td>
          <td> Spicy Crab Roll </td>              <td> 4.50 </td><td></td>
          <td> Spicy California Roll</td>         <td> 4.75 </td><td></td>
          <td> Cucumber Roll </td>                <td> 3.75</td><td></td>
        </tr><tr>
          <td> Avocado Roll </td>                 <td> 3.95 </td><td></td>
          <td> Asparagus Roll </td>               <td> 3.95 </td><td></td>
          <td> Crab Stick Roll </td>              <td> 3.95 </td><td></td>
          <td> Peanut Avocado Roll </td>          <td> 4.25</td><td></td>
        </tr><tr>
          <td></td><td></td><td></td>
          <td> Yellowtail Scallion Roll*          </td><td> 4.95 </td><td></td>
          <td></td><td></td><td></td>
          <td></td><td></td><td></td>
        </tr><tr>
          <th colspan="12" class="Subsection">Yamazaki Special Rolls</th>
        </tr><tr>
          <th colspan="12" class="SubSect2">Substitute: Brown Rice 0.5 Extra, Soybeen Wrap 1.00 Extra </th>
        </tr><tr>
          <td> Yamazaki Roll </td><td> 14.95 </td><td></td>
          <td> Honey Moon Roll</td><td> 13.95 </td><td></td>
          <td> Angry Dragon Roll </td><td> 12.95 </td><td></td>
          <td> Fire Roll </td><td> &nbsp; 9.95</td><td></td>
        </tr><tr>
          <td> American Dream Roll* </td><td> 11.95 </td><td></td>
          <td> Full Moon Roll</td><td>&nbsp; 9.50</td><td></td>
          <td> Columbus Roll </td><td>11.95 </td><td></td>
          <td> Sexy Girl Roll* </td><td> 10.95</td><td></td>
        </tr><tr>
          <td> Mango Salmon Roll* </td><td>&nbsp; 9.95 </td><td></td>
          <td> Candy Crush Roll*</td><td>11.95 </td><td></td>
          <td> Tuna Lover Roll* </td><td>10.95 </td><td></td>
          <td> Mango Tango Roll* </td><td>12.95</td><td></td>
        </tr><tr>
          <td> Pink Lady Roll* </td><td>12.25 </td><td></td>
          <td> Godzilla Roll</td><td>10.95 </td><td></td>
          <td> Yum-Yum  Roll </td><td>11.95 </td><td></td>
          <td> Kyoto Roll </td><td>11.95</td><td></td>
        </tr><tr>
          <td> Turtle Roll </td><td>11.50 </td><td></td>
          <td> Volcano Roll*</td><td>&nbsp; 10.95 </td><td></td>
          <td> Cherry Blossom </td><td>12.95</td><td></td>
          <td> Super Dragon Roll </td><td>11.95</td><td></td>
        </tr><tr>
          <td></td><td></td><td></td>
          <td> Crazy Roll</td><td>11.95 </td><td></td>
          <td> Summer Roll* </td><td>11.95 </td><td></td>
          <td></td><td></td><td></td>
        </tr><tr>
          <th colspan="12" class="Subsection">Sushi & Sashimi A La Carte</th>
        </tr><tr>
          <th colspan="12" class="SubSect2">2pc for sushi, 3pc for sushimi</th>
        </tr><tr>
          <td>Tuna*          </td><td colspan="2">4.95</td>
          <td>Salmon*        </td><td colspan="2">4.95</td>
          <td>Yellowtail*    </td><td colspan="2">4.95</td>
          <td>Shrimp         </td><td colspan="2">3.95</td>
        </tr><tr>
          <td>Crab stick     </td><td colspan="2">3.50</td>
          <td>Egg Cake       </td><td colspan="2">3.25</td>
          <td>Octopus*       </td><td colspan="2">4.00</td>
          <td> Black Flying Fish Roe*</td>        <td colspan="2">4.00</td>
        </tr><tr>
          <td>Mackerel*      </td><td colspan="2">3.95</td>
          <td>Smoked Salmon* </td><td colspan="2">4.75</td>
          <td>Scallop*       </td><td colspan="2">4.95</td>
          <td>Red Snapper*   </td><td colspan="2">3.75</td>
        </tr><tr>
          <td>Wasabi Tobikio*</td><td colspan="2">4.00</td>
          <td>White Tuna*    </td><td colspan="2">4.50</td>
          <td>Squid*         </td><td colspan="2">3.95</td>
          <td>Eel            </td><td colspan="2">4.95</td>
        </tr><tr>
          <td>Smelt Roe      </td><td colspan="2">3.95</td>
          <td>Salmon Roe     </td><td colspan="2">5.50</td>
          <td>Flying Fish Roe</td><td colspan="2">4.00</td>
          <td> </td><td colspan="2">4.00</td>
        </tr>


      </table>
      <table id="Lunch">
        <caption>Lunch</caption>
        <!--<caption class="subCap">Rice&Noodle</caption>-->
        <tr>
          <th colspan="12" class="Subsection">Kitchen Tempura Lunch</th>
        </tr><tr>
          <th colspan="12" class="SubSect2"> Served with Soup or Salad</th>
        </tr><tr>
          <td>Vegetable Tempura</td><td>6.95</td><td></td>
          <td>Chicken Tempura</td><td>7.95</td><td></td>
          <td>Shrimp Tempura</td><td>8.95</td><td></td>
          <td>Chicken Katsu</td><td>6.95</td><td></td>
        </tr><tr>
          <th colspan="12" class="Subsection">Hibachi Lunch</th>
        </tr><tr>
          <th colspan="12" class="SubSect2"> Served with Soup or Salad</th>
        </tr><tr>
          <td>Vegetable</td><td>&nbsp;6.95</td><td></td>
          <td>Tofu</td><td>&nbsp;7.25</td><td></td>
          <td>Chicken</td><td>&nbsp;8.25</td><td></td>
          <td>Shrimp(6)</td><td>&nbsp;8.95</td><td></td>
        </tr><tr>
          <td>Salmon</td><td>&nbsp;9.25</td><td></td>
          <td>Scallop(3)</td><td>&nbsp;9.25</td><td></td>
          <td>Steak*</td><td>11.25</td><td></td>
          <td>Lobster</td><td>11.95</td><td></td>
        </tr><tr>
          <td>Chicken & Shrimp </td><td>11.95</td><td></td>
          <td>Chicken & Salmon </td><td>12.95</td><td></td>
          <td>Chicken & Scallop </td><td>12.95</td><td></td>
          <td>Chicken & Steak* </td><td>13.95</td><td></td>
        </tr><tr>
          <th colspan="12" class="Subsection">Bento Box Lunch <span>(After 4pm add $2.00)</span> </th>
        </tr><tr>
          <th colspan="12" class="SubSect2"> Served with Soup, Salad, and rice (Steamed or Fried)</th>
        </tr><tr>
          <th colspan="12" class="SubSect2"> 2pc of Gyoza, 2pc Spring Roll, 8pc California Roll</th>
        </tr><tr>
          <td>Teriyaki Chicken</td><td>11.99</td><td></td>
          <td>Teriyaki Salmon </td><td>12.99</td><td></td>
          <td>Teriyaki Steak*</td><td>13.99</td><td></td>
          <td>Teriyaki Shrimp</td><td>12.99</td><td></td>
        </tr><tr>
          <td>Chicken Tempura(4)</td><td>11.99</td><td></td>
          <td>Shrimp Tempura(4)</td><td>12.99</td><td></td>
          <td>Chicken Katsu </td><td>11.99</td><td></td>
          <td>Sashimi(8)</td><td>12.99</td><td></td>
        </tr><tr>
          <th colspan="12" class="Subsection">Sushi Lunch Roll</th>
        </tr><tr>
          <th colspan="12" class="SubSect2"> Served with Soup or Salad</th>
        </tr><tr>
          <th colspan="12" class="SubSect2">Substitute: Brown Rice 0.5 Extra, Soybeen Wrap 1.00 Extra </th>
        </tr><tr>
          <th colspan="12" class="SubSect1">Any 2 Rolls: 8.95| Any 3 Rolls: 12.50</th>
        </tr><tr>
          <td colspan="3">*Tuna Roll</td>         <td colspan="3">*Salmon Roll</td>
          <td colspan="3">Eel Roll</td>           <td colspan="3">Shrimp Roll</td>
        </tr><tr>
          <td colspan="3">Snow crab Roll</td>     <td colspan="3">Mango Roll</td>
          <td colspan="3">Crab Roll</td>          <td colspan="3">Somked Salmon Roll*</td>
        </tr><tr>
          <td colspan="3">Cucumber Roll</td>      <td colspan="3">Avocado Roll</td>
          <td colspan="3">Yellowtail Roll*</td>   <td colspan="3">White Tuna Roll*</td>
        </tr><tr>
          <td colspan="3">AAC Roll</td>          <td colspan="3">Asparagus Roll</td>
          <td colspan="3">Easter Roll</td>       <td colspan="3">Boston Roll</td>
        </tr><tr>
          <td colspan="3">California Roll</td>    <td colspan="3">Peanut Avocado Roll</td>
          <td colspan="3">Philadelphia Roll*</td> <td colspan="3">Futomaki Roll</td>
        </tr><tr>
          <td colspan="3">Mixed Vegetable Roll</td><td colspan="3">Sweet Potato Roll</td>
          <td colspan="3">Shrimp Tempura Roll</td><td colspan="3">Vegetable Tempura Roll</td>
        </tr><tr>
          <td colspan="3">Crab Tempura Roll</td>  <td colspan="3">Salmon Tempura Roll</td>
          <td colspan="3">White Fish Tempura Roll</td><td colspan="3">Spicy Crap Stick Roll*</td>
        </tr><tr>
          <td colspan="3">Chicken Tempura Roll</td><td colspan="3">Spicy Tuna Roll*</td>
          <td colspan="3">Spicy Escolar Roll</td> <td colspan="3">Spicy Salmon Roll</td>
        </tr><tr>
          <td colspan="12"> Spicy California Roll</td>
        </tr><tr>
          <th colspan="12" class="Subsection">Sushi Lunch</th>
        </tr><tr>
          <th colspan="12" class="SubSect2"> Served with Soup or Salad</th>
        </tr><tr>
          <td>Sushi Plate*</td><td>10.50</td><td></td>
          <td>Sashimi Plate* </td><td>10.95</td><td></td>
          <td>Salmon Sushi Plate* </td><td>11.95</td><td></td>
          <td>Tuna Sushi Plate* </td><td>11.95</td><td></td>
        </tr><tr>
          <td></td><td></td><td></td>
          <td> White Tuna Sushi Plate*</td><td>11.50</td><td></td>
          <td> Sushi & Sashimi Combo Plate* </td><td>13.50</td><td></td>
          <td></td><td></td><td></td>
        </tr>
      </table>
      <table id="Kids">
        <caption>Kids</caption>
        <!--<caption class="subCap">Rice&Noodle</caption>-->
        <tr>
          <th colspan="12" class="Subsection"></th>
        </tr><tr>
          <th colspan="12" class="SubSect2"> Served with Fried or Steamed Rice</th>
        </tr><tr>
          <td>Vegetable</td><td> 4.95</td><td></td>
          <td>Chicken</td><td> 5.95</td><td></td>
          <td>Shrimp</td><td> 6.95</td><td></td>
        </tr><tr>
          <td>Salmon</td><td>6.95</td><td></td>
          <td>Scallop</td><td> 6.95</td><td></td>
          <td>Steak*</td><td> 8.95</td><td></td>
        </tr>
      </table>
      <table id="Desserts">
        <caption>Desserts</caption>
        <!--<caption class="subCap">Rice&Noodle</caption>-->
        <tr>
          <th colspan="12" class="Subsection"></th>
        </tr><tr>
          <td>Ice Cream</td><td> 1.99</td><td></td>
          <td>Mochi(4) </td><td> 3.75</td><td></td>
          <!--<td>Tempura Ice Cream</td><td>3.99</td>-->
        </tr>
      </table>
      <table id="Drinks">
        <caption>Drinks</caption>
        <tr>
          <th colspan="12" class="Subsection">Beverages $1.99</th>
        </tr><tr>
          <td colspan="2"> Coke                   </td>
          <td colspan="2"> Sprite                 </td>
          <td colspan="2"> Mellow Yello           </td>
          <td colspan="2"> Dr. Pepper             </td>
          <td colspan="2"> Lemonade               </td>
          <td colspan="2"> Dite Coke              </td>
        </tr><tr>
          <td colspan="2">                        </td>
          <td colspan="2"> Dite Coke              </td>
          <td colspan="2"> Ice Tea                </td>
          <td colspan="2"> Green Tea              </td>
          <td colspan="3"> Japanese Sprite        </td>
          <td>                                    </td>
        </tr><tr>
          <th colspan="12" class="Subsection"> Domestic Beer $3.25</th>
        </tr><tr>
          <td></td>
          <td colspan="2"> Coors Light            </td>
          <td colspan="2">Yuengling               </td>
          <td colspan="2">Bud Light               </td>
          <td colspan="2">Michelob Ultra          </td>
          <td colspan="2">Miller Light            </td>
          <td></td>
        </tr> <tr>
          <th colspan="12" class="Subsection"> Import Beer $4.25</th>
        </tr><tr>
          <td colspan="3">Sapporo                  </td>
          <td colspan="3">Asahi                    </td>
          <td colspan="3">Corona                   </td>
          <td colspan="3">Heineken                 </td>
        </tr> <tr>
          <th colspan="12" class="Subsection"> Sake(Hot or Cold)</th>
        </tr><tr>
          <td colspan="1">                         </td>
          <td colspan="3">Tyku Silver Sake         </td>
          <td colspan="1">6.99                     </td>
          <td colspan="1">                         </td>
          <td colspan="2">Bottle                   </td>
          <td colspan="1">27.99                    </td>
          <td colspan="3">                         </td>
        </tr><tr>
          <td colspan="1">                         </td>
          <td colspan="3">Tyku Cucumber            </td>
          <td colspan="1">8.99                     </td>
          <td colspan="1">                         </td>
          <td colspan="2">Bottle                   </td>
          <td colspan="1">29.99                    </td>
          <td colspan="1">                         </td>
        </tr><tr>
          <td colspan="1">                         </td>
          <td colspan="3">Tyku Coconut             </td>
          <td colspan="1">8.99                     </td>
          <td colspan="1">                         </td>
          <td colspan="2">Bottle                   </td>
          <td colspan="1">29.99                    </td>
          <td colspan="1">                         </td>
        </tr><tr>
          <th colspan="12" class="Subsection"> Wine</th>
        </tr><tr>
          <td colspan="2"> Twisted Chardonnay      </td>
          <td colspan="1"> glass                   </td>
          <td colspan="1"> 5.50                    </td>
          <td colspan="1"> bottle                  </td>
          <td colspan="1"> 28.99                   </td>
          <td colspan="2"> Twisted Pinot Grigio    </td>
          <td colspan="1"> glass                   </td>
          <td colspan="1"> 5.50                    </td>
          <td colspan="1"> bottle                  </td>
          <td colspan="1"> 28.99                   </td>
        </tr><tr>
          <td colspan="2"> Twisted Cabernet        </td>
          <td colspan="1"> glass                   </td>
          <td colspan="1"> 5.50                    </td>
          <td colspan="1"> bottle                  </td>
          <td colspan="1"> 28.99                   </td>
          <td colspan="2"> Twisted Merlot          </td>
          <td colspan="1"> glass                   </td>
          <td colspan="1"> 5.50                    </td>
          <td colspan="1"> bottle                  </td>
          <td colspan="1"> 28.99                   </td>
        </tr><tr>
          <td colspan="2"> Twisted Moscato         </td>
          <td colspan="1"> glass                   </td>
          <td colspan="1"> 5.50                    </td>
          <td colspan="1"> bottle                  </td>
          <td colspan="1"> 28.99                   </td>
          <td colspan="2"> Principato Pinot Noir   </td>
          <td colspan="1"> glass                   </td>
          <td colspan="1"> 5.50                    </td>
          <td colspan="1"> bottle                  </td>
          <td colspan="1"> 28.99                   </td>
        </tr>

      </table>
    </div>
    <br>
    <h1 id='raw'>*RAW or Cooked by Request</h1>
    <p id = 'raw'>Consuming raw or undercooked meats, beef, poultry, seafood, shellfish, or eggs may increase your risk of foodborne illness, especially if you have a certain medical conditions.</p>
    <footer>
      &copy; Yamazaki 2019
    </footer>
  <script type="application/javascript">
    window.onload = () => {
      startmenu();
    };
    function hideAllMenus() {
      const tables = document.getElementsByTagName('table');
      for (let table of tables) {
        table.setAttribute('hidden','true');
      }
    }
    function activateMenu(name) {
      const el = document.getElementById(name);
      if (el == null) { return; }
      hideAllMenus();
      el.removeAttribute('hidden');
    };
    function startmenu() {
      hideAllMenus();
      const start = document.getElementById('Entree');
      start.removeAttribute('hidden');
    }
    </script>
  </body>
</html>
